### ISSUE TITLE
ovos_listener cannot play start_listening file

### ISSUE THREAD

**Issue by atd** [OpenVoiceOS/ovos-docker#7] opened 2023-05-10 21:00 UTC
When wake word is triggered, no sound is played. There is the following trace in docker.

```
ovos_listener                | 2023-05-10 22:52:34.059 - voice - ovos_utils.sound:play_listening_sound:62 - WARNING - Could not find 'start_listening' audio file!
```

The file does exist in the `ovos_listener` container:

```
/home/ovos/.venv/lib/python3.11/site-packages/ovos_listener/res/snd/start_listening.wav
```

and the configuration seems too match:

```
Value: snd/start_listening.wav, found in /sounds/start_listening
```

Any ideas why the file is not found?

**Comment by goldyfruit** [comment] 2023-05-10 22:08
The file exists in the `ovos_listener` container:
```
ovos@f8a30d712825:/$ find / -name  start_listening.wav
/home/ovos/.venv/lib/python3.11/site-packages/ovos_listener/res/snd/start_listening.wav
```
The issue is related to the relative and absolute path, I opened an issue in `ovos-listener` repository about it [here](https://github.com/OpenVoiceOS/ovos-listener/issues/10).

Add this to your `mycroft.conf` configuration file.
```json
{
  "sounds": {
    "start_listening": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/start_listening.wav",
    "end_listening": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/end_listening.wav",
    "acknowledge": "/home/ovos/.venv/lib/python3.11/site-packages/ovos_dinkum_listener/res/snd/acknowledge.mp3"
  }
}

**Comment by goldyfruit** [comment] 2023-05-13 21:52
Feel free to re-open the issue if its not fixed by the information provided from above. :+1:

**Closed as completed by goldyfruit** 2023-05-13 21:52 UTC
Labels: not-an-issue

**Comment by atd** [comment] 2023-05-14 17:30
Thank you, it worked (using `ovos_listener` instead of `ovos_dinkum_listener`)
